// rpc.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: shift.proto

package shift

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义获取航班信息的请求头
type GetShiftReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShiftNumber string `protobuf:"bytes,1,opt,name=shiftNumber,proto3" json:"shiftNumber,omitempty"`
	Date        string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetShiftReq) Reset() {
	*x = GetShiftReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shift_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShiftReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShiftReq) ProtoMessage() {}

func (x *GetShiftReq) ProtoReflect() protoreflect.Message {
	mi := &file_shift_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShiftReq.ProtoReflect.Descriptor instead.
func (*GetShiftReq) Descriptor() ([]byte, []int) {
	return file_shift_proto_rawDescGZIP(), []int{0}
}

func (x *GetShiftReq) GetShiftNumber() string {
	if x != nil {
		return x.ShiftNumber
	}
	return ""
}

func (x *GetShiftReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

//定义获取航班信息的返回体
type GetShiftRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShiftNumber string `protobuf:"bytes,1,opt,name=shiftNumber,proto3" json:"shiftNumber,omitempty"`
	Date        string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	TakeoffTime string `protobuf:"bytes,3,opt,name=takeoffTime,proto3" json:"takeoffTime,omitempty"`
	LandingTime string `protobuf:"bytes,4,opt,name=landingTime,proto3" json:"landingTime,omitempty"`
}

func (x *GetShiftRsp) Reset() {
	*x = GetShiftRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shift_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShiftRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShiftRsp) ProtoMessage() {}

func (x *GetShiftRsp) ProtoReflect() protoreflect.Message {
	mi := &file_shift_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShiftRsp.ProtoReflect.Descriptor instead.
func (*GetShiftRsp) Descriptor() ([]byte, []int) {
	return file_shift_proto_rawDescGZIP(), []int{1}
}

func (x *GetShiftRsp) GetShiftNumber() string {
	if x != nil {
		return x.ShiftNumber
	}
	return ""
}

func (x *GetShiftRsp) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetShiftRsp) GetTakeoffTime() string {
	if x != nil {
		return x.TakeoffTime
	}
	return ""
}

func (x *GetShiftRsp) GetLandingTime() string {
	if x != nil {
		return x.LandingTime
	}
	return ""
}

var File_shift_proto protoreflect.FileDescriptor

var file_shift_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x68, 0x69, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x68, 0x69, 0x66, 0x74, 0x22, 0x43, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x69, 0x66, 0x74, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x68, 0x69, 0x66, 0x74, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x68, 0x69,
	0x66, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x68, 0x69, 0x66, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x61, 0x6b, 0x65, 0x6f, 0x66, 0x66, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x6b, 0x65, 0x6f, 0x66, 0x66, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54,
	0x69, 0x6d, 0x65, 0x32, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x68, 0x69,
	0x66, 0x74, 0x12, 0x12, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x73, 0x68, 0x69, 0x66, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x69, 0x66, 0x74, 0x52, 0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x73, 0x68, 0x69, 0x66, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shift_proto_rawDescOnce sync.Once
	file_shift_proto_rawDescData = file_shift_proto_rawDesc
)

func file_shift_proto_rawDescGZIP() []byte {
	file_shift_proto_rawDescOnce.Do(func() {
		file_shift_proto_rawDescData = protoimpl.X.CompressGZIP(file_shift_proto_rawDescData)
	})
	return file_shift_proto_rawDescData
}

var file_shift_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shift_proto_goTypes = []interface{}{
	(*GetShiftReq)(nil), // 0: shift.GetShiftReq
	(*GetShiftRsp)(nil), // 1: shift.GetShiftRsp
}
var file_shift_proto_depIdxs = []int32{
	0, // 0: shift.GetShiftService.GetShift:input_type -> shift.GetShiftReq
	1, // 1: shift.GetShiftService.GetShift:output_type -> shift.GetShiftRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shift_proto_init() }
func file_shift_proto_init() {
	if File_shift_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shift_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShiftReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shift_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShiftRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shift_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shift_proto_goTypes,
		DependencyIndexes: file_shift_proto_depIdxs,
		MessageInfos:      file_shift_proto_msgTypes,
	}.Build()
	File_shift_proto = out.File
	file_shift_proto_rawDesc = nil
	file_shift_proto_goTypes = nil
	file_shift_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GetShiftServiceClient is the client API for GetShiftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetShiftServiceClient interface {
	GetShift(ctx context.Context, in *GetShiftReq, opts ...grpc.CallOption) (*GetShiftRsp, error)
}

type getShiftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetShiftServiceClient(cc grpc.ClientConnInterface) GetShiftServiceClient {
	return &getShiftServiceClient{cc}
}

func (c *getShiftServiceClient) GetShift(ctx context.Context, in *GetShiftReq, opts ...grpc.CallOption) (*GetShiftRsp, error) {
	out := new(GetShiftRsp)
	err := c.cc.Invoke(ctx, "/shift.GetShiftService/GetShift", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetShiftServiceServer is the server API for GetShiftService service.
type GetShiftServiceServer interface {
	GetShift(context.Context, *GetShiftReq) (*GetShiftRsp, error)
}

// UnimplementedGetShiftServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGetShiftServiceServer struct {
}

func (*UnimplementedGetShiftServiceServer) GetShift(context.Context, *GetShiftReq) (*GetShiftRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShift not implemented")
}

func RegisterGetShiftServiceServer(s *grpc.Server, srv GetShiftServiceServer) {
	s.RegisterService(&_GetShiftService_serviceDesc, srv)
}

func _GetShiftService_GetShift_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShiftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetShiftServiceServer).GetShift(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/shift.GetShiftService/GetShift",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetShiftServiceServer).GetShift(ctx, req.(*GetShiftReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetShiftService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "shift.GetShiftService",
	HandlerType: (*GetShiftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetShift",
			Handler:    _GetShiftService_GetShift_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shift.proto",
}
